version: '3.2'
services:
  mysql80:
    container_name: "mysql80"
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: appdb
        MYSQL_ROOT_PASSWORD: secret
        TZ: 'Asia/Tokyo'
    ports:
      - "3306"
    restart: always
    volumes:
      - "../db:/var/lib/mysql"
      - "../logs:/var/log/mysql"
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"

  testdb:
    container_name: "testdb"
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql
    restart: always
    environment:
        MYSQL_DATABASE: testing
        MYSQL_ROOT_PASSWORD: secret
        TZ: 'Asia/Tokyo'

  nginx:
    container_name: "nginx"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - "./public:/app/public/"
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    restart: always

  php-fpm:
    container_name: "php-fpm"
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - "./:/app/"
    restart: always
    links:
     - mysql80
     - redis

  pma:
    container_name: "pma"
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql80
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql80
    links:
      - mysql80


  redis:
    restart: always
    image: redis:latest
    volumes:
      - ../redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes


  nginx_for_schemaspy:
    image: nginx:1.13.9-alpine
    container_name: nginx_for_schemaspy
    volumes:
      - ./schemaspy:/var/www/html:ro
      - ./docker/nginx_for_schemaspy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"
    depends_on:
      - schemaspy
  schemaspy:
    build: ./docker/schemaspy
    image: treetips/schemaspy-mysql
    container_name: schemaspy
    volumes:
      - ./schemaspy:/app/html:rw
      - ./docker/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    working_dir: "/app"
    command: "java -jar schemaspy.jar"
    links:
     - mysql80
